#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# exit 0

# npx --no-install commitlint --edit "$1"

#!/bin/sh.
"$(dirname "$0")/_/husky.sh"
echo "========= 执行commit-msg校验 ======="

npx --no-install commitlint --edit $1
